spring:
  application:
    name: pwr-view-profile-service
  jackson:
    serialization:
      write_dates_as_timestamps: false
  servlet:
    multipart:
      max-file-size: 128MB
      max-request-size: 128MB
  main:
    allow-bean-definition-overriding: true # We need to enable this for openfeign fallbacks
server:
  port: 9008
eureka:
  client:
    enabled: true
management:
  endpoints:
    web:
      cors:
        allowed-methods: '*'
        allowed-origins: '*'
      base-path: /meta/actuator
feign:
  hystrix:
    enabled: true
# Increase the timeout for communication with the report service so it doesn't die during report generation
pwr-report-service:
  ribbon:
    ReadTimeout: 20000
    ConnectTimeout: 10000
hystrix:
 command:
   default:
     execution:
       timeout:
         enabled: "false"
       isolation:
         strategy: "THREAD"
         thread:
           timeoutInMilliseconds: "20000"
---
spring:
  profiles: localDev
  redis:
    host: localhost
    port: 6379
    database: 6
logging:
  level:
    de.hbt.pwr.view.aspects: DEBUG
debug: false
eureka:
  client:
    enabled: true
    service-url:
       defaultZone: http://power02.corp.hbt.de:8761/eureka
---
spring:
  profiles: test
  redis:
    host: localhost
    port: 6379
    database: 5
eureka:
  client:
    enabled: false

