spring:
  application:
    name: pwr-view-profile-service
  jackson:
    serialization:
      write_dates_as_timestamps: false
  servlet:
    multipart:
      max-file-size: 128MB
      max-request-size: 128MB
  main:
    allow-bean-definition-overriding: true # We need to enable this for openfeign fallback
  redis:
    host: ${DB_HOST}
    port: ${DB_PORT}
    database: ${DB_DATABASE}
server:
  port: 9008
management:
  endpoints:
    web:
      cors:
        allowed-methods: '*'
        allowed-origins: '*'
pwr-profile-service-url: http://pwr-profile-service:9004
pwr-skill-service-url: http://pwr-skill-service:9003
pwr-report-service-url: http://pwr-report-service:9005
---
spring:
  profiles: localDev
  redis:
    host: localhost
    port: 6379
    database: 6
    password: changeit
logging:
  level:
    root: info
    de.hbt.pwr.view: debug
debug: false
pwr-skill-service-url: http://localhost:9003
pwr-profile-service-url: http://localhost:9004
pwr-report-service-url: http://localhost:9005
---
spring:
  profiles: test
  redis:
    host: localhost
    port: 6379
    database: 5
