name: Java CI
on:
  push:
    branches:
      - master
      - docker
      - development
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 13
      uses: actions/setup-java@v1
      with:
        java-version: 13
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - uses: nelonoel/branch-name@v1
    - name: Build & Push to Docker Hub
      uses: zenato/docker-action@v1.0.0
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: "docker.pkg.github.com"
        repository: hbtgmbh/pwr-view-profile-service/pwr-view-profile-service
        tag: ${{env.BRANCH_NAME}}
